runtime: nodejs16

instance_class: F2


env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: '?)FfMA??%<tsU^Q?'
  INSTANCE_CONNECTION_NAME: 'daryllukaslabs:europe-central2:wazz-gud-db'
  CLOUDINARY_NAME: 'dj4l2tiuw'
  CLOUDINARY_KEY: '589117612291255'
  CLOUDINARY_SECRET: 'KfgWsfrlg2CDtwcu_bId9bzsBKI'

beta_settings:
  cloud_sql_instances: daryllukaslabs:europe-central2:wazz-gud-db'